# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo, and live in the nix-project flake. It is callable, so what is
# particular to this project is all that is left to say.
{
  description = "An xclip-style Wayland clipboard tool written in Rust";

  inputs.project.url = "github:overby-me/nix-project";

  outputs = inputs:
    inputs.project ./. {
      name = "wclip";
      description = "An xclip-style Wayland clipboard tool written in Rust";
    };
}
