# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo, and live in the nix-workspace flake. It is callable, so what is
# particular to this project is all that is left to say.
{
  description = "An xclip-style Wayland clipboard tool written in Rust";

  inputs = {
    workspace.url = "git+https://tangled.org/overby.me/nix-workspace";

    # Declaring nix-lib is the whole of opting into the fine-grained
    # per-crate build; the input carries the builder and its index.
    nix-lib = {
      url = "git+https://tangled.org/overby.me/nix-lib";
      inputs.workspace.follows = "workspace";
    };
  };

  outputs = inputs:
    inputs.workspace {
      name = "wclip";
      description = "An xclip-style Wayland clipboard tool written in Rust";
      inherit inputs;
    };
}
